default_agent: core_demo
agents:
  core_demo:
    name: core_demo
    entrypoint: /Users/zoherer/Desktop/Source/agentcoredemo/agentcore-runtime-quickstart/strands/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::028195660756:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-3da8703eea
      execution_role_auto_create: false
      account: 028195660756
      region: us-west-2
      ecr_repository: 028195660756.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-core_demo
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: core_demo-rorP9g76dQ
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:028195660756:runtime/core_demo-rorP9g76dQ
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-core_demo-builder
      execution_role: arn:aws:iam::028195660756:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-3da8703eea
      source_bucket: bedrock-agentcore-codebuild-sources-028195660756-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
